version: '3'

services:
  #service 1: definition of mysql database
  mysql-db:
    image: mysql:latest
    container_name: "mysql-db"
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=mediscreen-patient
      - MYSQL_USER=sqluser
      - MYSQL_PASSWORD=Sql2015
    ports:
      - 3322:3306
    restart: always
  mediscreen-patient:
    image: mediscreen-patient
    container_name: mediscreen-patient
    restart: on-failure
    ports:
      - 8081:8081
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/mediscreen-patient?UTC&createDatabaseIfNotExist=TRUE&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      - mysql-db
