version: '3'

services:
  #service 1: definition of mysql database
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=mediscreen-patient
      - MYSQL_USER=sqluser
      - MYSQL_PASSWORD=Sql2015
    #ports:
      - "3307:3306"
    restart: always
  mediscreen-patient:
    image: mediscreen-patient
    container_name: mediscreen-patient
    ports:
      - 8081:8081
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-db
    links:
      - mysql-db
